### ISSUE TITLE
create table test cases

### ISSUE THREAD

**Issue by tantaman** [aphrodite-sh/cr-sqlite#2]
Create a repository of create table statements that flex all the various edge cases:
- default values (int, string, float, null, blob, hex blob, non hex blob)
- multi col primary keys
- no cols
- not null constraints
- no primary keys
- all part of primary key
- ...

and run crr, view, trigger, etc. tests against it.

**Comment by Rock-liyi** [comment]
Hi, tantaman  
 Nice to meet you , i am rock ,  i focus on decentralized database domain, and look for some people who have similar ideals and beliefs.  I’m one of the authors of the decentralized database [P2PDB](https://github.com/Rock-liyi/p2pdb)   i'd like to make a  friend with you, do you have  any contact way  that  I can   contact you with ,such wechat、twitter、telegram

**Comment by tantaman** [comment]
@Rock-liyi  - https://twitter.com/Tantaman if you want to send me a message request.

**Comment by tantaman** [comment]
this is no longer required given the new approach of not needing to parse create table statements.
